# remote: the endpoint from which the proxy receives the stream
# localdelivery: the local endpoint where the proxy delivers the stream
# for playing purpose (e.g., VLC or MPV)

# remote=localhost:8888
# localdelivery=localhost:7777

remote=localhost:8888
localdelivery=localhost:7777

servercontrol=localhost:9999
movie=cars.dat




