# remote: the endpoint from which the proxy receives the stream
# localdelivery: the local endpoint where the proxy delivers the stream
# for playing purpose (e.g., VLC or MPV)

# remote=127.0.0.1:8888
# localdelivery=127.0.0.1:7777

remote=127.0.0.1:8888
localdelivery=127.0.0.1:7777

servercontrol=127.0.0.1:9999
movie=cars.dat




